# SITE CONFIGURATION
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://gvdr.github.io" # the base hostname & protocol for your site

gems:
  - jemoji

# THEME-SPECIFIC CONFIGURATION
theme:
  # Meta
  title: gvdr
  avatar: avatar.png
  gravatar: # 8cc255a53f7205b9b99448bed9150da0 email md5 hash
  description: "The web nest of Giulio Valentino Dalla Riva" # used by search engines
  
  #I'm a biomathematician PhD student exploring the evolving web of life.
  # Header and footer text
  header_text: >
     <p>Hello world!</p>
     <p>As you may have noticed, this website is still work in progress. </p>
     <p>You can already read some info about <a href="http://gvdr.github.io/about/">me</a>. </p>
     <p>I will be posting here updates about my <a href="http://gvdr.github.io/science/">research</a>. </p>
     <p>Now and then I am tempted to share my <a href="http://gvdr.github.io/blog/">thoughts</a> about science, politics, music, the universe and everything else. But I will mainly write about mathematics, evolution and ecology. Ant that's probably enough! </p>

  footer_text: >
   This goofy website has been created using <a href="http://jekyllrb.com">Jekyll</a> with <a href="https://rohanchandra.github.io/project/type/">Type Theme</a> on a Linux machine.
  
  # Icons
  rss: true
  email_address: gvd16@uclive.ac.nz # full email address, e.g. "sam@example.com"
  behance:
  bitbucket: 
  dribbble: 
  facebook: 
  flickr: 
  github: "gvdr/"
  google_plus: 
  instagram: 
  linkedin:  # full URL
  pinterest: 
  reddit: 
  soundcloud: 
  stack_exchange:  # full URL
  steam: 
  tumblr: 
  twitter: "ipnosimmia"
  wordpress: 
  youtube: 
  
  # Scripts
  google_analytics: # tracking id, e.g. "UA-000000-01"
  disqus_shortname:
  
  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  str_next: "Next"
  str_prev: "Prev"
  str_continue_reading: "Continue reading"
  
  # Colors, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"

permalink: /:categories/:title

# PAGINATION
paginate: 5
paginate_path: "blog/page:num"

# BUILD SETTINGS
markdown: kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: :compressed
